version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  app:
    restart: on-failure
    build: ./app
    ports:
      - '5000:5000'
  web:
    build: ./web
    ports:
    - '80:9001'
    depends_on:
    - web