version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    expose:
      - '6379'
  app:
    restart: on-failure
    build: ./app
    expose:
      - '8000'
  web:
    build: ./web
    ports:
    - '9001:9001'
    depends_on:
    - app