version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web:
    restart: on-failure
    build: ./web
    ports:
      - '5000:5000'
  nginx:
    build: ./nginx
    ports:
    - '9001:9001'
    depends_on:
    - web